### ISSUE TITLE
Allow to select names for log event properties

### ISSUE THREAD

**Issue by vlkornev** [RehanSaeed/Serilog.Enrichers.Span#104] opened 2022-01-24 14:10 UTC
### Describe the feature

It is valuable to be able to configure log event properties names instead of hardcoded consts.
.Enrich.WithSpan(new SpanOptions{LogEventPropertiesNames = new SpanLogEventPropertiesNames
            {
                ParentId = "@corr-parent-id",
                SpanId = "@corr-span-id ",
                TraceId = "@corr-trace-id"
            }})

**Comment by vlkornev** [comment] 2022-01-24 15:00
I would like to contribute, but I cannot push a branch for review

**Comment by RehanSaeed** [comment] 2022-01-25 09:16
Seems like a duplicate of https://github.com/RehanSaeed/Serilog.Enrichers.Span/issues/28.

To submit a PR, you need to fork the repo, create a branch on your fork and then submit that as a PR.

**Closed by RehanSaeed** 2022-01-25 09:16 UTC
Labels: enhancement
